FROM node:lts-alpine
ENV NODE_ENV=production

WORKDIR /app
COPY ["./server/package.json", "./server/package-lock.json*", "./server/npm-shrinkwrap.json*", "./"]
RUN ls
RUN npm install --production
COPY ./server .
EXPOSE 4000 80
RUN chown -R node /app
USER node
CMD ["npm", "start"]
