version: '3.4'

services:
  nodeReactDocker:
    image: ah363702/node-react-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      JWT_KEY: dsafasdklfj
      MONGO_URI: ''
      PORT: 4000
    ports:
      - 4000:4000
