FROM node:lts-alpine
ENV NODE_ENV=production
ENV MONGO_HOST "host.docker.internal"
ENV ROOT_URL=http://localhost
WORKDIR /usr/src/app
COPY ["./server/package.json", "./server/package-lock.json*", "./server/npm-shrinkwrap.json*", "./"]
RUN npm install --production && mv node_modules ../
COPY . .
EXPOSE 2222 80
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
