# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - react-docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - run: cd ./client && npm install && cd ..
    - run: cd ./server && npm install && npm run build:client && npm run test:ci

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0c12e74172ec469c849fcd43ab90c0f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18aef25a94e64f7ba566f9796dd7d89e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0c12e74172ec469c849fcd43ab90c0f2 }}/ah363702/node-react-docker:${{ github.sha }}
        # tags: ah363702/${{ secrets.AzureAppService_ContainerUsername_0c12e74172ec469c849fcd43ab90c0f2 }}/ah363702/node-react-docker:latest
        file: ./server/Dockerfile.prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'react-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f7d8e155aff6431a85bc97f8cacf6f09 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0c12e74172ec469c849fcd43ab90c0f2 }}/ah363702/node-react-docker:${{ github.sha }}'
